- name: Replace ssl.conf configure
  become: true
  ansible.builtin.template:
    src: templates/httpd.conf.j2
    dest: "/etc/httpd/conf.d/{{ letsencrypt_fqdn }}.conf"
    owner: apache
    group: apache
    mode: '0644'
  notify: Restart httpd
