- name: Replace ssl.conf configure
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/conf.d/{{ letsencrypt_fqdn }}.conf"
    owner: nginx
    group: nginx
    mode: '0644'
  notify: Restart nginx
